### ISSUE TITLE
how to reproduce the results on vqa_RAD

### ISSUE THREAD

**Issue by ljpadam** [jiangsongtao/TinyMed#6]
Thank you for publishing this great work.
I have several issues about reproducing the results on vqa_RAD.

1) I found the model weights are removed from the huggingface repo.
![image](https://github.com/jiangsongtao/TinyMed/assets/4587516/f1e1a708-0ceb-4cc2-8425-25a65072ad14)

2) What is the difference between MoE-Tinymed-phi2-llava and llavaphi-2.7b-finetune-3epoch?

3) I have to change the "mm_image_tower": "/data/songtao/clip-vit-large-patch14-336" to "mm_image_tower": "openai/clip-vit-large-patch14-336" in the config file, otherwise the testing script can not be run. Is it the right way?

4) Which --conv-mode should be used? The "simple" one used in the readme example can not be found in the codes.

5) Which models should be used to reproduce the results in Table 2 in your paper?

**Comment by jiangsongtao** [comment]
Hello! Due to some files not being uploaded correctly to Hugging Face when using the VPN earlier, I have just re-uploaded them. I have updated the conversations.py file to add the simple option for conv_mode. You need to download the stage2 and stage3 models, then update the vit and model path in the config file (your third step of modifying the vit path should be correct). Our Table 2 results were produced using the stage3 model.
