### ISSUE TITLE
How to reproduce the results of zero-shot?

### ISSUE THREAD

**Issue by AlexandreWANG915** [jiangsongtao/TinyMed#8]
First, I want to thank you for your excellent work with TinyMed. 

I've been working with TinyMed and have a few questions:

1. How can I reproduce the zero-shot results? I tried using the stage 2 weights in the hugging face and then using the same command and model_vqa_med.py file as in stage 3 to generate answers, but I got an error saying the weights don't match.

2. I've noticed that the stage 3 results have some discrepancies compared to the results reported in the paper, especially for open-ended questions. Do you have any suggestions on how to reduce this gap?

3. I've noticed a small issue in the code: in the llava_stablelm_moe.py file, it seems that MOE should be imported from moe.layer rather than from deepspeed.

Thank you for your time and for sharing this valuable work with the community.

**Comment by jiangsongtao** [comment]
Hello, thank you for your interest in Med-MoE.

For question 1: Could you please provide the specific error message?

For question 2: In our previous old version, the open-setting performance was not as high as in the current paper version because we made new designs in the MoE architecture in the new version (we will upload the updated code and weights to Huggingface after finalizing them). The weights currently available on Huggingface are from the old version.

For question 3: Thank you for your feedback; we have already corrected it.

**Comment by AlexandreWANG915** [comment]
Thank you for your prompt reply. I rerun the code, and I found that the filename of weight is very important, and I have already reproduced the results of zero-shot. However, for the stage 3 evaluation, it seems like there are some weights are not initialized. I wonder if it is because you modify the model. The other question is why the answer in Stage 2 is much longer than in Stage 3.  
<img width="1324" alt="Snipaste_2024-07-14_11-18-20" src="https://github.com/user-attachments/assets/fdb533ad-9006-46e7-90fb-42bf32b53596">

**Comment by AlexandreWANG915** [comment]
Thanks! For question 2, I have the following question. I used the stage 2 model to describe the downstream task dataset, e.g., Slake. I used the prompt "Analyze the image in a comprehensive and detailed manner.", but it seems like the model could not distinguished by different images, just output the same answers. For this question, do you have any insights? I think in the pre-training phase, the model should have the ability to describe medical images.
<img width="1732" alt="image" src="https://github.com/user-attachments/assets/581845a1-0e74-4c4b-9ad9-271510d3f6e3">

**Comment by jiangsongtao** [comment]
Hello! Perhaps you can try different conv-mode parameters, such as 'simple', or try prompts like "Describe xxx in detail," similar to the prompt types in the stage1 and stage2 training data. Due to the limited scale of the training data, the model's ability to follow instructions is not as strong as in general MLLMs.

**Comment by jiangsongtao** [comment]
Hi, I will close this issue for now. If you have any further questions, please feel free to open a new one.
